services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
    - ./backend:/var/www
      - /var/www/vendor
    environment:
      DB_PATH: /var/www/storage/database.sqlite
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker
    command: php app/Workers/run-cleaner.php
    volumes:
    - ./backend:/var/www
      - /var/www/vendor
    environment:
      DB_PATH: /var/www/storage/database.sqlite
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped