services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www:Z
      - backend_vendor:/var/www/vendor
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker
    command: php app/Workers/run-cleaner.php
    volumes:
    - ./backend:/var/www:Z
    - backend_vendor:/var/www/vendor
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: soketi
    env_file:
      - ./backend/.env
    ports:
      - "6001:6001"
      - "9601:9601"
    restart: unless-stopped

volumes:
  backend_vendor: